import React from 'react'

function Write() {
    return (
        <div className='mt-24 container mx-auto flex flex-col items-start gap-5'>

            <p className='tracking-wider text-neutral-300'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis nisl et urna dignissim, id aliquet urna sollicitudin. Proin vehicula metus ac augue luctus, vel blandit metus lacinia. Duis tristique ex in elit auctor, a tincidunt lectus malesuada. Sed eget nunc eu risus sollicitudin tincidunt. Donec id felis in neque bibendum hendrerit. Nam non libero vel nulla fermentum consectetur. Curabitur feugiat magna non magna suscipit, a ultricies sapien pulvinar. Aenean ac nibh nec nulla auctor congue. Morbi nec felis in purus gravida auctor et in ligula. Sed ut nulla et felis scelerisque posuere.
                Nullam tempor turpis et massa posuere, id tempor justo volutpat. In porttitor nunc id lorem fringilla, ac dapibus ex tincidunt. Suspendisse in eros vitae turpis posuere tincidunt. Maecenas non urna in velit aliquam ullamcorper. Integer dignissim magna id ante tincidunt, at fermentum elit sagittis. Fusce luctus tortor et velit bibendum, ac dapibus nulla blandit. Ut bibendum libero a metus fermentum, in pharetra felis molestie. Integer semper urna nec risus volutpat, a viverra eros fringilla. Aenean non felis sed odio hendrerit aliquam. Vivamus id lacus ac est bibendum lacinia. Phasellus facilisis justo vitae orci bibendum, ut sodales justo tristique. Sed et velit ultricies, iaculis libero in, dapibus nisl. Duis vitae mi id sem pulvinar condimentum at sit amet orci. Pellentesque vulputate sapien ac urna fringilla, vel fermentum nunc dignissim.
                Etiam vehicula lorem ac metus vestibulum, et vehicula nisi dictum. Donec consectetur dolor ut elit sodales, non pharetra augue tempor. Proin vulputate elit ac lectus viverra, eget vehicula sem congue. Curabitur elementum ipsum a tincidunt lacinia. Sed vel ligula ac lectus posuere congue et id nisi. Donec non mi eu lorem varius hendrerit. Mauris volutpat odio a justo aliquam, nec malesuada elit dictum. Ut ac ligula eget est posuere egestas nec sed felis. In sed libero quis velit consectetur bibendum.
                Curabitur facilisis metus id odio fermentum, at sollicitudin arcu ultricies. Maecenas cursus dui nec turpis ultrices scelerisque. Sed vel tortor nec felis consectetur aliquam. Vestibulum finibus odio in purus convallis, ac finibus nisl vehicula. Etiam at tortor nec magna ullamcorper bibendum. Nam vestibulum magna euismod, iaculis felis sed, venenatis magna. Cras faucibus odio at urna pretium, et ultricies sem fermentum. Vivamus efficitur lacus at libero consequat, nec dictum arcu aliquet. Aenean at ex et erat aliquam tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
                Nullam imperdiet ligula in ex viverra, vel consequat quam bibendum. Suspendisse potenti. Ut aliquam urna vitae orci tincidunt vehicula. Fusce at felis lacinia, dapibus libero eu, tempor lorem. Pellentesque tincidunt dolor nec nisl efficitur, nec vehicula felis pretium. Quisque tristique elit id sapien consequat, nec iaculis ex varius. Nunc vehicula risus ac felis pharetra, non porttitor orci fringilla. Aliquam a magna id tortor dignissim ultricies non a felis. Sed sed turpis nec ligula porttitor sodales nec eget ipsum. Nam vel erat non lorem consequat fermentum. Suspendisse ut augue vel dui feugiat vestibulum ut in turpis. Nunc finibus urna vel sem condimentum, at aliquam leo hendrerit. Maecenas dapibus elit in lacus fermentum, et tincidunt eros iaculis. Mauris convallis justo et nisl posuere, at fermentum erat facilisis.
            </p>

            <img src="/Collection/contact.png" alt="blog middle" className='w-full h-96 object-cover' />

            <p className='tracking-wider text-neutral-300'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis nisl et urna dignissim, id aliquet urna sollicitudin. Proin vehicula metus ac augue luctus, vel blandit metus lacinia. Duis tristique ex in elit auctor, a tincidunt lectus malesuada. Sed eget nunc eu risus sollicitudin tincidunt. Donec id felis in neque bibendum hendrerit. Nam non libero vel nulla fermentum consectetur. Curabitur feugiat magna non magna suscipit, a ultricies sapien pulvinar. Aenean ac nibh nec nulla auctor congue. Morbi nec felis in purus gravida auctor et in ligula. Sed ut nulla et felis scelerisque posuere.
                Nullam tempor turpis et massa posuere, id tempor justo volutpat. In porttitor nunc id lorem fringilla, ac dapibus ex tincidunt. Suspendisse in eros vitae turpis posuere tincidunt. Maecenas non urna in velit aliquam ullamcorper. Integer dignissim magna id ante tincidunt, at fermentum elit sagittis. Fusce luctus tortor et velit bibendum, ac dapibus nulla blandit. Ut bibendum libero a metus fermentum, in pharetra felis molestie. Integer semper urna nec risus volutpat, a viverra eros fringilla. Aenean non felis sed odio hendrerit aliquam. Vivamus id lacus ac est bibendum lacinia. Phasellus facilisis justo vitae orci bibendum, ut sodales justo tristique. Sed et velit ultricies, iaculis libero in, dapibus nisl. Duis vitae mi id sem pulvinar condimentum at sit amet orci. Pellentesque vulputate sapien ac urna fringilla, vel fermentum nunc dignissim.
                Etiam vehicula lorem ac metus vestibulum, et vehicula nisi dictum. Donec consectetur dolor ut elit sodales, non pharetra augue tempor. Proin vulputate elit ac lectus viverra, eget vehicula sem congue. Curabitur elementum ipsum a tincidunt lacinia. Sed vel ligula ac lectus posuere congue et id nisi. Donec non mi eu lorem varius hendrerit. Mauris volutpat odio a justo aliquam, nec malesuada elit dictum. Ut ac ligula eget est posuere egestas nec sed felis. In sed libero quis velit consectetur bibendum.
                Curabitur facilisis metus id odio fermentum, at sollicitudin arcu ultricies. Maecenas cursus dui nec turpis ultrices scelerisque. Sed vel tortor nec felis consectetur aliquam. Vestibulum finibus odio in purus convallis, ac finibus nisl vehicula. Etiam at tortor nec magna ullamcorper bibendum. Nam vestibulum magna euismod, iaculis felis sed, venenatis magna. Cras faucibus odio at urna pretium, et ultricies sem fermentum. Vivamus efficitur lacus at libero consequat, nec dictum arcu aliquet. Aenean at ex et erat aliquam tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
                Nullam imperdiet ligula in ex viverra, vel consequat quam bibendum. Suspendisse potenti. Ut aliquam urna vitae orci tincidunt vehicula. Fusce at felis lacinia, dapibus libero eu, tempor lorem. Pellentesque tincidunt dolor nec nisl efficitur, nec vehicula felis pretium. Quisque tristique elit id sapien consequat, nec iaculis ex varius. Nunc vehicula risus ac felis pharetra, non porttitor orci fringilla. Aliquam a magna id tortor dignissim ultricies non a felis. Sed sed turpis nec ligula porttitor sodales nec eget ipsum. Nam vel erat non lorem consequat fermentum. Suspendisse ut augue vel dui feugiat vestibulum ut in turpis. Nunc finibus urna vel sem condimentum, at aliquam leo hendrerit. Maecenas dapibus elit in lacus fermentum, et tincidunt eros iaculis. Mauris convallis justo et nisl posuere, at fermentum erat facilisis.
            </p>

        </div>
    )
}

export default Write